language: node_js
env:
  - VERSION="0.8"
  - VERSION="0.10"
  - VERSION="iojs"
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm --version
  - nvm install $VERSION
  - node --version
  - '[ "${VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm
  - npm --version
sudo: false
